### ISSUE TITLE
"Latest" version picks up old releases

### ISSUE THREAD

**Issue by xeraa** [acidvegas/elastop#14]
Latest (at least for me) currently displays 8.15.5 though 8.16.1 has been out for a bit.

I don't think the logic in https://github.com/acidvegas/elastop/blob/4bbf0c6bf13626561270c16cce423794592dc507/elastop.go#L291-L312 will work since we might do additional patch level releases for previous minor or major releases, so a "latest" release based on time might display those instead of the "highest" version number.

**Comment by acidvegas** [comment]
This is due to the weird way Elasticsearch pushes releases.

According to the API response from Github on https://api.github.com/repos/elastic/elasticsearch/releases/latest, they mark 8.15 as the latest.

Even when you visit https://github.com/elastic/elasticsearch/releases, 8.15 is marked as the latest.

But I do see 8.16 has been out. Maybe they consider it beta still?

**Comment by xeraa** [comment]
No it's not beta, it's a stable release. Let me ask what we're doing there (I work for Elastic).

PS: We've just released 8.17, so right now that's "latest". But when we do a patch for a previous version, we'll probably have that as latest again.

**Comment by acidvegas** [comment]
Cheers! Nice to meet someone else from Elasticsearch. My company has done a lot of communication with you guys.

Yeah please let me know. It's confusing cause I know even ES 7 is still getting updates if I'm not mistaken. I have noticed this in the past where a latest release for ES 7 was marked as the "latest" release for the whole repo.
